disabled = false
languageCode = "zh-cn"
languageName = "Chinese"
weight = 1
title = "YinMo19's Blog"

[params]
displayName = "Chinese"
isoCode = "zh-cn"
rtl = false
dateFormat = "2 January 2006"

["params.author"]
name = "YinMo19"
headline = "Rust, ARM ASM, and Mac."
image = "avatar.png"
links = [{ github = "https://github.com/YinMo19" }]
